### ISSUE TITLE
Create the Test container to backend unit test

### ISSUE THREAD

**Issue by kirubeltadesse** [Swarmies/sap-core#65]
# Description 

Create a container a `test` and just run the tests in the `svc` container.

## Acceptable Criteria 

- creating test container
- only focusing on the backend
- run locally and see if that works

## Related Story 

This is the first container to run unit tests separately. 

## Technical Info

There is a sample code that will be added to the `docker-compose.yml` file. 

```
test:
   build: .
   init: true
   volumes:
       -  same as the svc
   command:
       - /path/to/python
       - -m
       - pytest
       - tests
    depends_on:
       - svc
```

There is additional resource about [pytest](https://docs.pytest.org/en/stable/getting-started.html)
